# These pairs are needed to ensure the bias arising from the convolution decomposition are added to the correct BN
conv_bn_pairs = {'conv1': 'bn1.running_mean',
                 'layer1.0.conv1': 'layer1.0.bn1.running_mean',
                 'layer1.0.conv2': 'layer1.0.bn2.running_mean',
                 'layer1.0.conv3': 'layer1.0.bn3.running_mean',
                 'layer1.0.downsample.conv.conv': 'layer1.0.downsample.bnorm.bnorm.running_mean',
                 'layer1.1.conv1': 'layer1.1.bn1.running_mean',
                 'layer1.1.conv2': 'layer1.1.bn2.running_mean',
                 'layer1.1.conv3': 'layer1.1.bn3.running_mean',
                 'layer1.2.conv1': 'layer1.2.bn1.running_mean',
                 'layer1.2.conv2': 'layer1.2.bn2.running_mean',
                 'layer1.2.conv3': 'layer1.2.bn3.running_mean',

                 'layer2.0.conv1': 'layer2.0.bn1.running_mean',
                 'layer2.0.conv2': 'layer2.0.bn2.running_mean',
                 'layer2.0.conv3': 'layer2.0.bn3.running_mean',
                 'layer2.0.downsample.conv.conv': 'layer2.0.downsample.bnorm.bnorm.running_mean',
                 'layer2.1.conv1': 'layer2.1.bn1.running_mean',
                 'layer2.1.conv2': 'layer2.1.bn2.running_mean',
                 'layer2.1.conv3': 'layer2.1.bn3.running_mean',
                 'layer2.2.conv1': 'layer2.2.bn1.running_mean',
                 'layer2.2.conv2': 'layer2.2.bn2.running_mean',
                 'layer2.2.conv3': 'layer2.2.bn3.running_mean',
                 'layer2.3.conv1': 'layer2.3.bn1.running_mean',
                 'layer2.3.conv2': 'layer2.3.bn2.running_mean',
                 'layer2.3.conv3': 'layer2.3.bn3.running_mean',

                 'layer3.0.conv1': 'layer3.0.bn1.running_mean',
                 'layer3.0.conv2': 'layer3.0.bn2.running_mean',
                 'layer3.0.conv3': 'layer3.0.bn3.running_mean',
                 'layer3.0.downsample.conv.conv': 'layer3.0.downsample.bnorm.bnorm.running_mean',
                 'layer3.1.conv1': 'layer3.1.bn1.running_mean',
                 'layer3.1.conv2': 'layer3.1.bn2.running_mean',
                 'layer3.1.conv3': 'layer3.1.bn3.running_mean',
                 'layer3.2.conv1': 'layer3.2.bn1.running_mean',
                 'layer3.2.conv2': 'layer3.2.bn2.running_mean',
                 'layer3.2.conv3': 'layer3.2.bn3.running_mean',
                 'layer3.3.conv1': 'layer3.3.bn1.running_mean',
                 'layer3.3.conv2': 'layer3.3.bn2.running_mean',
                 'layer3.3.conv3': 'layer3.3.bn3.running_mean',
                 'layer3.4.conv1': 'layer3.4.bn1.running_mean',
                 'layer3.4.conv2': 'layer3.4.bn2.running_mean',
                 'layer3.4.conv3': 'layer3.4.bn3.running_mean',
                 'layer3.5.conv1': 'layer3.5.bn1.running_mean',
                 'layer3.5.conv2': 'layer3.5.bn2.running_mean',
                 'layer3.5.conv3': 'layer3.5.bn3.running_mean',

                 'layer4.0.conv1': 'layer4.0.bn1.running_mean',
                 'layer4.0.conv2': 'layer4.0.bn2.running_mean',
                 'layer4.0.conv3': 'layer4.0.bn3.running_mean',
                 'layer4.0.downsample.conv.conv': 'layer4.0.downsample.bnorm.bnorm.running_mean',
                 'layer4.1.conv1': 'layer4.1.bn1.running_mean',
                 'layer4.1.conv2': 'layer4.1.bn2.running_mean',
                 'layer4.1.conv3': 'layer4.1.bn3.running_mean',
                 'layer4.2.conv1': 'layer4.2.bn1.running_mean',
                 'layer4.2.conv2': 'layer4.2.bn2.running_mean',
                 'layer4.2.conv3': 'layer4.2.bn3.running_mean',
                 }